### ISSUE TITLE
bug: empty PR description

### ISSUE THREAD

**Issue by anrico-oltmanns** [devops-infra/action-pull-request#112]
## :memo:  Brief description

We merge everything to `develop`. Once a week we merge everything from `develop` to `master`. This weekly `master merge` contains 50+ commits from 10+ issues with 10+ pull requests. In our weekly `master merge` we want a description with all the related `issues` or related `PRs`. I tried different actions, tools or ways to do that. Now Im trying to use your action (which we already use for the weekly `master merge`). I tried using different actions where the output should be the related `PRs` and use this output in the `body` of your action. I tried using different outputs (url or PR number) of your action but nothing seems to work. Im pretty new to all of this but for my understanding im doing everything correctly. Once again, I tried a bunch of different things... The `body` is just always empty when I look into the logs. Is it a bug? Am I doing something wrong? Is it outdated? Here is a screenshot of my action:

![Screenshot 2023-01-30 120654](https://user-images.githubusercontent.com/114996994/215460755-50d28263-1ede-4a2e-9a25-ebd5eeed700c.png)

This is a test repository with a PAT with most of the permissions. Im just trying to change the body. The comments are some things I tested before but they didnt work either. 

## :warning: Checklist
* [ ] Provided a clear and concise description of what the issue is.
* [ ] Given a clear and concise description of what is expected.
* [ ] Proposed a clear and concise description of any alternative solutions or other features.
* [ ] Added any other context or screenshots about the feature request.
* [ ] Associated pull request has been already created and link was provided.

*Check [CONTRIBUTING.md][contributing] and [CODE_OF_CONDUCT.md][code] for more information*

[contributing]: https://github.com/devops-infra/.github/blob/master/CONTRIBUTING.md
[code]: https://github.com/devops-infra/.github/blob/master/CODE_OF_CONDUCT.md

**Comment by ChristophShyper** [comment]
Hello! Thank you for using my action.

Are you sure the previous action is setting the outputs properly?
Maybe you can try to debug it in your `vars` step and just print it there.

I've run this:
```yaml
      - name: Test
        id: test
        run: |
          outval="Test value\nSecond line\nThird line"
          echo "outval=$outval" >> $GITHUB_OUTPUT

      - name: Create pull request - test
        uses: devops-infra/action-pull-request@v0.5.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          body: ${{ steps.test.outputs.outval }}
```

And it created the PR properly 
![image](https://user-images.githubusercontent.com/45788587/215500055-73689161-0b7a-4400-b054-b731d7772f4a.png)
