### ISSUE TITLE
Bug: Job fails but still creates the PR 

### ISSUE THREAD

**Issue by 7tupel** [devops-infra/action-pull-request#123]
##  Description

Running the Action at the latest version (0.5.5) runs into an error. While GH shows an error, the PR is correctly created and visible in the PR view on GH. This step is the last in my workflow, so not critical at the moment, but it is not exactly helpful when a workflow run always shows as failed while it actually achieved what it should have.

## Details

Error in the log (last two lines in the job's log):
```
Error updating issue: Unprocessable Entity (HTTP 422)
Invalid value for "name"
```

Job configuration in the workflow:
```
- name: Create Release PR
        id: create-pull-request 
        uses: devops-infra/action-pull-request@v0.5.5
        with:
          github_token: ${{ github.token }}
          target_branch: 'master'
          source_branch: 'release-${{ steps.timestamp.outputs.time }}'
          title: '[RELEASE] Create a new Release'
          body: Auto-generated by the _Create Release PR_ Action
          label: automated pr, release
          assignee: 7tupel
```

The output referenced in `source_branch` is correctly set and is correctly used by the action to create the PR.

My repository is public and available here: https://github.com/ClockworksIO/clci
