### ISSUE TITLE
Pull request not triggering workflow

### ISSUE THREAD

**Issue by vinayprakash893** [devops-infra/action-pull-request#125]
Im using the below actions in one of the workflow

      - name: Create PR
        #if: startsWith(github.ref, 'refs/heads/feature')
        uses: devops-infra/action-pull-request@v0.5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          title: ${{ github.event.commits[0].message }}
          assignee: ${{ github.actor }}
          label: automatic,feature
          # template: .github/PULL_REQUEST_TEMPLATE/FEATURE.md
          old_string: "**Write you description here**"
          new_string: ${{ github.event.commits[0].message }}
          get_diff: true
          target_branch: main
          
        
in the same repo i have another workflow which triggers when the pull request is created to main

```
  name: secondworflow.yaml
   on: 
    push:
      branches: [ main ]
    pull_request_target:
      types: [assigned, opened, synchronize, reopened]
      branches:
        - main
        - 'release/**'
    workflow_dispatch:
  
  permissions:
    id-token: write
    contents: read
    issues: write
    pull-requests: write
      
  jobs:
    build:
      *********
```
    
 
 manually creating pull request to main is triggering the seconfworflow, but the PR's which are created using this action is not triggering,
