### ISSUE TITLE
Can I add multiple reviewers ?

### ISSUE THREAD

**Issue by SanderDevisscher** [devops-infra/action-pull-request#150]
## :memo:  Brief description
When I add more than 1 user (see code below) as reviewer the action doesn't add any. I would like to add multiple users to review the pull request.
- is it possible to add multiple reviewers ?
- is there a syntax error in my code?

```
- name: Create pull request
        uses: devops-infra/action-pull-request@v0.4.2
        with:
          github_token: ${{ secrets.AUTOMATISATION }}
          target_branch: uat
          title: "[AUTO] PR title"
          template: path to PR template.md
          reviewer: username1, username2, username3
          label: automated workflow
          get_diff: false
```
