### ISSUE TITLE
Help with labels-with-spaces

### ISSUE THREAD

**Issue by mathomp4** [devops-infra/action-pull-request#53]
## :memo:  Brief description

I'm currently using this cool action to try and automate some processes for a code I work on. And so far, so good. But on this repo we have a changelog enforcer action as well but for the auto PRs I'd like to "skip" the changelog enforcer as in this case, I don't care. 

That said, I seem to be dumb at trying to do this. The label is "Skip Changelog" and I added to my yaml:
```yaml
          label: automatic,MAPL3,"Skip Changelog"
```

But, when I tried it out in a tester repo, the action applied just "Skip":

https://github.com/mathomp4/labeltest/pull/35

What is the correct way to handle labels with spaces in them?
 
## :warning: Checklist
* [x] Provided a clear and concise description of what the issue is.
* [ ] Given a clear and concise description of what is expected.
* [ ] Proposed a clear and concise description of any alternative solutions or other features.
* [ ] Added any other context or screenshots about the feature request.
* [ ] Associated pull request has been already created and link was provided.

*Check [CONTRIBUTING.md][contributing] and [CODE_OF_CONDUCT.md][code] for more information*

[contributing]: https://github.com/devops-infra/.github/blob/master/CONTRIBUTING.md
[code]: https://github.com/devops-infra/.github/blob/master/CODE_OF_CONDUCT.md

**Comment by ChristophShyper** [comment]
Hello. I'm very happy that you find my action useful :)

Here is example of a test configuration:
```yml
      - name: Create pull request - test (conditional)
        if: startsWith(github.ref, 'refs/heads/test')
        uses: devops-infra/action-pull-request@v0.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          assignee: "${{ github.actor }}"
          reviewer: "${{ github.actor }}"
          label: test,not1hing not2thing,'sin1gle sin2gle',"dou1ble dou2ble",test2
          template: .github/PULL_REQUEST_TEMPLATE.md
          get_diff: true
```

And the result is
![image](https://user-images.githubusercontent.com/45788587/129636870-421a1d97-e194-4cfb-b6b3-cb5b6786d130.png)

Double quotes totally ruin parsing. Internally it's just splitting the string by the comma `,` character. So to create multi-word label it's enough to just do it without any quotation marks.

In your case following code should work just fine.
```yml
label: automatic,MAPL3,Skip Changelog
```
